/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
 import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdActualizar.setEnabled(false);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        txtRetirar.setEditable(false);
        txtIngresar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdIngresar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdSiguiente = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        txtIngresar = new javax.swing.JTextField();
        txtRetirar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel1.setText("Saravia's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, -1));

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        jPanel2.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, -1));

        txtCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));

        jLabel2.setText("Identificación del usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Saldo inicial");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setText("Numero de cuenta");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 310, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Opciones")));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, -1));

        cmdActualizar.setText("Actualizar saldo");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        cmdSiguiente.setText("Siguiente");
        cmdSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSiguienteActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        jPanel3.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel3.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 250, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 36, 520, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 590, 150));

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel7.setText("Bank");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(708, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        Cuenta c;
        int cuenta,id;
        double ingresos,saldo,saldonuevo;
       if (txtIngresar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la cantidad a agregar", "error", JOptionPane.ERROR_MESSAGE);
            txtIngresar.requestFocusInWindow();
        }else{ 
         cuenta = Integer.parseInt(txtCuenta.getText());
        id = Integer.parseInt(txtId.getText());
        saldo = Double.parseDouble(txtSaldo.getText());
        ingresos=Double.parseDouble(txtIngresar.getText());
        c = new Cuenta(cuenta, id, saldo);
         
                        c.ingresar(ingresos);
                    txtSaldo.setText(c.renovar());     
                txtArea.setText(c.mostrar());
                
                
       }
                  
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSiguienteActionPerformed
        if (txtCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Número de cuenta", "error", JOptionPane.ERROR_MESSAGE);
            txtCuenta.requestFocusInWindow();
        } else if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Número de identificación del cliente", "error", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocusInWindow();
        } else if (Integer.parseInt(txtId.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "El número de Identificación del cliente no puede ser cero", "error", JOptionPane.ERROR_MESSAGE);
            txtId.requestFocusInWindow();
            txtId.selectAll();
        } else if (txtSaldo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Saldo Actual de la cuenta, si la cuenta no tiene saldo digite 0 por favor", "error", JOptionPane.ERROR_MESSAGE);
            txtSaldo.requestFocusInWindow();
     
        }else{
            
        cmdActualizar.setEnabled(true);
        cmdIngresar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        txtSaldo.setEditable(false);
        txtCuenta.setEditable(false);
        txtId.setEditable(false);
        txtRetirar.setEditable(true);
        txtIngresar.setEditable(true);
        }
    }//GEN-LAST:event_cmdSiguienteActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        Cuenta c; 
        int cuenta,id;
        double retiro,saldo;
        if (txtRetirar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la cantidad a retirar", "error", JOptionPane.ERROR_MESSAGE);
            txtRetirar.requestFocusInWindow();
        }else{  
        cuenta = Integer.parseInt(txtCuenta.getText());
        id = Integer.parseInt(txtId.getText());
        saldo = Double.parseDouble(txtSaldo.getText());
        retiro=Double.parseDouble(txtRetirar.getText());
        
        c = new Cuenta(cuenta, id, saldo);
        
         if(retiro>saldo){
             JOptionPane.showMessageDialog(this,"Saldo insuficiente, no se puede hacer el retiro","error",JOptionPane.ERROR_MESSAGE);
         }else{               
          c.retirar(retiro);
              }            
                txtSaldo.setText(c.renovar()); 
                txtArea.setText(c.mostrar ());
         
        }
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        Cuenta c;
        String res;
        int cuenta,id;
        double saldo,interes,actualizado;
        cuenta = Integer.parseInt(txtCuenta.getText());
        id = Integer.parseInt(txtId.getText());
        saldo = Double.parseDouble(txtSaldo.getText());
        
        c = new Cuenta(cuenta, id, saldo);
                JOptionPane.showMessageDialog(this, "Saldo actualizado correctamente");
                c.acturalizar(12);
                txtSaldo.setText(c.renovar()); 
                txtArea.setText(c.mostrar());
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        cmdActualizar.setEnabled(false);
        cmdIngresar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        txtSaldo.setEditable(true);
        txtCuenta.setEditable(true);
        txtId.setEditable(true);
        txtRetirar.setEditable(false);
        txtIngresar.setEditable(false);
        txtArea.setText("");
        txtCuenta.setText("");
        txtCuenta.requestFocusInWindow();
        txtId.setText("");
        txtSaldo.setText("");
        txtIngresar.setText("");
        txtRetirar.setText("");
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyTyped
         char c=evt.getKeyChar();
             
         
          if(!Character.isDigit(evt.getKeyChar())) { 
              getToolkit().beep(); 
               
              evt.consume(); 
          }
    }//GEN-LAST:event_txtCuentaKeyTyped

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
      char c=evt.getKeyChar();
             
         
          if(!Character.isDigit(evt.getKeyChar())) { 
              getToolkit().beep(); 
               
              evt.consume(); 
          }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
       char c = evt.getKeyChar();

        if ((!Character.isDigit(c)) && (evt.getKeyChar() != '.')) {
            getToolkit().beep();
            evt.consume();

        }
        if (evt.getKeyChar() == '.' && txtSaldo.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        Cuenta c; 
         int cuenta,id;
        double saldo,interes,actualizado;
        cuenta = Integer.parseInt(txtCuenta.getText());
        id = Integer.parseInt(txtId.getText());
        saldo = Double.parseDouble(txtSaldo.getText()); 
        c = new Cuenta(cuenta, id, saldo);
         txtSaldo.setText(c.renovar()); 
                
                txtArea.setText(c.mostrar());
         
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
        char c = evt.getKeyChar();

        if ((!Character.isDigit(c)) && (evt.getKeyChar() != '.')) {
            getToolkit().beep();
            evt.consume();

        }
        if (evt.getKeyChar() == '.' && txtSaldo.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtIngresarKeyTyped

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        char c = evt.getKeyChar();

        if ((!Character.isDigit(c)) && (evt.getKeyChar() != '.')) {
            getToolkit().beep();
            evt.consume();

        }
        if (evt.getKeyChar() == '.' && txtSaldo.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtRetirarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JButton cmdSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
